name: generic-mocks

deployments:
  ethereum:
    goerli:
      - contract_type: MockToken
        address: 0xeB6e6DC9a4A19A3d78A753c788E9dc84802bA844
      - contract_type: MockNFT
        address: 0xCaAf44843Ce103FC8fdD9d19a96612D020705208

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.3

solidity: 
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.7.3"

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5
